name: React App CI/CD to AWS EC2 via SCP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set Yarn version
        run: |
          corepack enable
          yarn set version 4.9.2

      # 2. Node.js 환경 설정
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "yarn"

      #

      # 3. 의존성 설치 및 React 앱 빌드
      - name: Install dependencies and build
        run: |
          yarn
          yarn build
        env:
          CI: false

      # 4. SCP를 사용하여 빌드 파일 전송 및 배포
      - name: Deploy to EC2 instance via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "build/*" # build 디렉토리 안의 모든 파일을 전송
          target: "/var/www/ysh33" # EC2의 웹 서버 루트 디렉토리

      # 5. EC2에 접속하여 웹 서버 재시작
      - name: Restart web server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart nginx
